/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as VersioningRouteImport } from './routes/versioning'
import { Route as VersionDiffRouteImport } from './routes/version-diff'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as QueryRouteImport } from './routes/query'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactAnalysisRouteImport } from './routes/impact-analysis'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DiffRouteImport } from './routes/diff'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BaselineRouteImport } from './routes/baseline'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestNewRouteImport } from './routes/test.new'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as ReqNewRouteImport } from './routes/req.new'
import { Route as ReqReqIdRouteImport } from './routes/req.$reqId'
import { Route as PrintTestsRouteImport } from './routes/print.tests'
import { Route as PrintRequirementsRouteImport } from './routes/print.requirements'
import { Route as PrintQueryResultRouteImport } from './routes/print.query-result'
import { Route as PrintImpactAnalysisRouteImport } from './routes/print.impact-analysis'
import { Route as PrintDashboardRouteImport } from './routes/print.dashboard'
import { Route as PrintCampaignReportRouteImport } from './routes/print.campaign-report'
import { Route as PrintCampaignPlanRouteImport } from './routes/print.campaign-plan'
import { Route as CampaignNewRouteImport } from './routes/campaign.new'
import { Route as CampaignCampaignIdRouteImport } from './routes/campaign.$campaignId'
import { Route as CampaignCampaignIdRunTestIdRouteImport } from './routes/campaign.$campaignId_.run.$testId'
import { Route as CampaignCampaignIdExecuteTestIdRouteImport } from './routes/campaign.$campaignId_.execute.$testId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const VersioningRoute = VersioningRouteImport.update({
  id: '/versioning',
  path: '/versioning',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionDiffRoute = VersionDiffRouteImport.update({
  id: '/version-diff',
  path: '/version-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryRoute = QueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactAnalysisRoute = ImpactAnalysisRouteImport.update({
  id: '/impact-analysis',
  path: '/impact-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffRoute = DiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BaselineRoute = BaselineRouteImport.update({
  id: '/baseline',
  path: '/baseline',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNewRoute = TestNewRouteImport.update({
  id: '/test/new',
  path: '/test/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReqNewRoute = ReqNewRouteImport.update({
  id: '/req/new',
  path: '/req/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReqReqIdRoute = ReqReqIdRouteImport.update({
  id: '/req/$reqId',
  path: '/req/$reqId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintTestsRoute = PrintTestsRouteImport.update({
  id: '/print/tests',
  path: '/print/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRequirementsRoute = PrintRequirementsRouteImport.update({
  id: '/print/requirements',
  path: '/print/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQueryResultRoute = PrintQueryResultRouteImport.update({
  id: '/print/query-result',
  path: '/print/query-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintImpactAnalysisRoute = PrintImpactAnalysisRouteImport.update({
  id: '/print/impact-analysis',
  path: '/print/impact-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintDashboardRoute = PrintDashboardRouteImport.update({
  id: '/print/dashboard',
  path: '/print/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCampaignReportRoute = PrintCampaignReportRouteImport.update({
  id: '/print/campaign-report',
  path: '/print/campaign-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCampaignPlanRoute = PrintCampaignPlanRouteImport.update({
  id: '/print/campaign-plan',
  path: '/print/campaign-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignNewRoute = CampaignNewRouteImport.update({
  id: '/campaign/new',
  path: '/campaign/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdRoute = CampaignCampaignIdRouteImport.update({
  id: '/campaign/$campaignId',
  path: '/campaign/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignCampaignIdRunTestIdRoute =
  CampaignCampaignIdRunTestIdRouteImport.update({
    id: '/campaign/$campaignId_/run/$testId',
    path: '/campaign/$campaignId/run/$testId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignCampaignIdExecuteTestIdRoute =
  CampaignCampaignIdExecuteTestIdRouteImport.update({
    id: '/campaign/$campaignId_/execute/$testId',
    path: '/campaign/$campaignId/execute/$testId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baseline': typeof BaselineRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/diff': typeof DiffRoute
  '/graph': typeof GraphRoute
  '/impact-analysis': typeof ImpactAnalysisRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/product': typeof ProductRoute
  '/query': typeof QueryRoute
  '/requirements': typeof RequirementsRoute
  '/schema': typeof SchemaRoute
  '/search': typeof SearchRoute
  '/tests': typeof TestsRoute
  '/version-diff': typeof VersionDiffRoute
  '/versioning': typeof VersioningRoute
  '/workspace': typeof WorkspaceRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/campaign/new': typeof CampaignNewRoute
  '/print/campaign-plan': typeof PrintCampaignPlanRoute
  '/print/campaign-report': typeof PrintCampaignReportRoute
  '/print/dashboard': typeof PrintDashboardRoute
  '/print/impact-analysis': typeof PrintImpactAnalysisRoute
  '/print/query-result': typeof PrintQueryResultRoute
  '/print/requirements': typeof PrintRequirementsRoute
  '/print/tests': typeof PrintTestsRoute
  '/req/$reqId': typeof ReqReqIdRoute
  '/req/new': typeof ReqNewRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test/new': typeof TestNewRoute
  '/campaign/$campaignId/execute/$testId': typeof CampaignCampaignIdExecuteTestIdRoute
  '/campaign/$campaignId/run/$testId': typeof CampaignCampaignIdRunTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baseline': typeof BaselineRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/diff': typeof DiffRoute
  '/graph': typeof GraphRoute
  '/impact-analysis': typeof ImpactAnalysisRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/product': typeof ProductRoute
  '/query': typeof QueryRoute
  '/requirements': typeof RequirementsRoute
  '/schema': typeof SchemaRoute
  '/search': typeof SearchRoute
  '/tests': typeof TestsRoute
  '/version-diff': typeof VersionDiffRoute
  '/versioning': typeof VersioningRoute
  '/workspace': typeof WorkspaceRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/campaign/new': typeof CampaignNewRoute
  '/print/campaign-plan': typeof PrintCampaignPlanRoute
  '/print/campaign-report': typeof PrintCampaignReportRoute
  '/print/dashboard': typeof PrintDashboardRoute
  '/print/impact-analysis': typeof PrintImpactAnalysisRoute
  '/print/query-result': typeof PrintQueryResultRoute
  '/print/requirements': typeof PrintRequirementsRoute
  '/print/tests': typeof PrintTestsRoute
  '/req/$reqId': typeof ReqReqIdRoute
  '/req/new': typeof ReqNewRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test/new': typeof TestNewRoute
  '/campaign/$campaignId/execute/$testId': typeof CampaignCampaignIdExecuteTestIdRoute
  '/campaign/$campaignId/run/$testId': typeof CampaignCampaignIdRunTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/baseline': typeof BaselineRoute
  '/compliance': typeof ComplianceRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardRoute
  '/diff': typeof DiffRoute
  '/graph': typeof GraphRoute
  '/impact-analysis': typeof ImpactAnalysisRoute
  '/login': typeof LoginRoute
  '/preferences': typeof PreferencesRoute
  '/product': typeof ProductRoute
  '/query': typeof QueryRoute
  '/requirements': typeof RequirementsRoute
  '/schema': typeof SchemaRoute
  '/search': typeof SearchRoute
  '/tests': typeof TestsRoute
  '/version-diff': typeof VersionDiffRoute
  '/versioning': typeof VersioningRoute
  '/workspace': typeof WorkspaceRoute
  '/campaign/$campaignId': typeof CampaignCampaignIdRoute
  '/campaign/new': typeof CampaignNewRoute
  '/print/campaign-plan': typeof PrintCampaignPlanRoute
  '/print/campaign-report': typeof PrintCampaignReportRoute
  '/print/dashboard': typeof PrintDashboardRoute
  '/print/impact-analysis': typeof PrintImpactAnalysisRoute
  '/print/query-result': typeof PrintQueryResultRoute
  '/print/requirements': typeof PrintRequirementsRoute
  '/print/tests': typeof PrintTestsRoute
  '/req/$reqId': typeof ReqReqIdRoute
  '/req/new': typeof ReqNewRoute
  '/test/$testId': typeof TestTestIdRoute
  '/test/new': typeof TestNewRoute
  '/campaign/$campaignId_/execute/$testId': typeof CampaignCampaignIdExecuteTestIdRoute
  '/campaign/$campaignId_/run/$testId': typeof CampaignCampaignIdRunTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/baseline'
    | '/compliance'
    | '/components'
    | '/dashboard'
    | '/diff'
    | '/graph'
    | '/impact-analysis'
    | '/login'
    | '/preferences'
    | '/product'
    | '/query'
    | '/requirements'
    | '/schema'
    | '/search'
    | '/tests'
    | '/version-diff'
    | '/versioning'
    | '/workspace'
    | '/campaign/$campaignId'
    | '/campaign/new'
    | '/print/campaign-plan'
    | '/print/campaign-report'
    | '/print/dashboard'
    | '/print/impact-analysis'
    | '/print/query-result'
    | '/print/requirements'
    | '/print/tests'
    | '/req/$reqId'
    | '/req/new'
    | '/test/$testId'
    | '/test/new'
    | '/campaign/$campaignId/execute/$testId'
    | '/campaign/$campaignId/run/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/baseline'
    | '/compliance'
    | '/components'
    | '/dashboard'
    | '/diff'
    | '/graph'
    | '/impact-analysis'
    | '/login'
    | '/preferences'
    | '/product'
    | '/query'
    | '/requirements'
    | '/schema'
    | '/search'
    | '/tests'
    | '/version-diff'
    | '/versioning'
    | '/workspace'
    | '/campaign/$campaignId'
    | '/campaign/new'
    | '/print/campaign-plan'
    | '/print/campaign-report'
    | '/print/dashboard'
    | '/print/impact-analysis'
    | '/print/query-result'
    | '/print/requirements'
    | '/print/tests'
    | '/req/$reqId'
    | '/req/new'
    | '/test/$testId'
    | '/test/new'
    | '/campaign/$campaignId/execute/$testId'
    | '/campaign/$campaignId/run/$testId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/baseline'
    | '/compliance'
    | '/components'
    | '/dashboard'
    | '/diff'
    | '/graph'
    | '/impact-analysis'
    | '/login'
    | '/preferences'
    | '/product'
    | '/query'
    | '/requirements'
    | '/schema'
    | '/search'
    | '/tests'
    | '/version-diff'
    | '/versioning'
    | '/workspace'
    | '/campaign/$campaignId'
    | '/campaign/new'
    | '/print/campaign-plan'
    | '/print/campaign-report'
    | '/print/dashboard'
    | '/print/impact-analysis'
    | '/print/query-result'
    | '/print/requirements'
    | '/print/tests'
    | '/req/$reqId'
    | '/req/new'
    | '/test/$testId'
    | '/test/new'
    | '/campaign/$campaignId_/execute/$testId'
    | '/campaign/$campaignId_/run/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BaselineRoute: typeof BaselineRoute
  ComplianceRoute: typeof ComplianceRoute
  ComponentsRoute: typeof ComponentsRoute
  DashboardRoute: typeof DashboardRoute
  DiffRoute: typeof DiffRoute
  GraphRoute: typeof GraphRoute
  ImpactAnalysisRoute: typeof ImpactAnalysisRoute
  LoginRoute: typeof LoginRoute
  PreferencesRoute: typeof PreferencesRoute
  ProductRoute: typeof ProductRoute
  QueryRoute: typeof QueryRoute
  RequirementsRoute: typeof RequirementsRoute
  SchemaRoute: typeof SchemaRoute
  SearchRoute: typeof SearchRoute
  TestsRoute: typeof TestsRoute
  VersionDiffRoute: typeof VersionDiffRoute
  VersioningRoute: typeof VersioningRoute
  WorkspaceRoute: typeof WorkspaceRoute
  CampaignCampaignIdRoute: typeof CampaignCampaignIdRoute
  CampaignNewRoute: typeof CampaignNewRoute
  PrintCampaignPlanRoute: typeof PrintCampaignPlanRoute
  PrintCampaignReportRoute: typeof PrintCampaignReportRoute
  PrintDashboardRoute: typeof PrintDashboardRoute
  PrintImpactAnalysisRoute: typeof PrintImpactAnalysisRoute
  PrintQueryResultRoute: typeof PrintQueryResultRoute
  PrintRequirementsRoute: typeof PrintRequirementsRoute
  PrintTestsRoute: typeof PrintTestsRoute
  ReqReqIdRoute: typeof ReqReqIdRoute
  ReqNewRoute: typeof ReqNewRoute
  TestTestIdRoute: typeof TestTestIdRoute
  TestNewRoute: typeof TestNewRoute
  CampaignCampaignIdExecuteTestIdRoute: typeof CampaignCampaignIdExecuteTestIdRoute
  CampaignCampaignIdRunTestIdRoute: typeof CampaignCampaignIdRunTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versioning': {
      id: '/versioning'
      path: '/versioning'
      fullPath: '/versioning'
      preLoaderRoute: typeof VersioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version-diff': {
      id: '/version-diff'
      path: '/version-diff'
      fullPath: '/version-diff'
      preLoaderRoute: typeof VersionDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-analysis': {
      id: '/impact-analysis'
      path: '/impact-analysis'
      fullPath: '/impact-analysis'
      preLoaderRoute: typeof ImpactAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff': {
      id: '/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseline': {
      id: '/baseline'
      path: '/baseline'
      fullPath: '/baseline'
      preLoaderRoute: typeof BaselineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/new': {
      id: '/test/new'
      path: '/test/new'
      fullPath: '/test/new'
      preLoaderRoute: typeof TestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/req/new': {
      id: '/req/new'
      path: '/req/new'
      fullPath: '/req/new'
      preLoaderRoute: typeof ReqNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/req/$reqId': {
      id: '/req/$reqId'
      path: '/req/$reqId'
      fullPath: '/req/$reqId'
      preLoaderRoute: typeof ReqReqIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/tests': {
      id: '/print/tests'
      path: '/print/tests'
      fullPath: '/print/tests'
      preLoaderRoute: typeof PrintTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/requirements': {
      id: '/print/requirements'
      path: '/print/requirements'
      fullPath: '/print/requirements'
      preLoaderRoute: typeof PrintRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/query-result': {
      id: '/print/query-result'
      path: '/print/query-result'
      fullPath: '/print/query-result'
      preLoaderRoute: typeof PrintQueryResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/impact-analysis': {
      id: '/print/impact-analysis'
      path: '/print/impact-analysis'
      fullPath: '/print/impact-analysis'
      preLoaderRoute: typeof PrintImpactAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/dashboard': {
      id: '/print/dashboard'
      path: '/print/dashboard'
      fullPath: '/print/dashboard'
      preLoaderRoute: typeof PrintDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/campaign-report': {
      id: '/print/campaign-report'
      path: '/print/campaign-report'
      fullPath: '/print/campaign-report'
      preLoaderRoute: typeof PrintCampaignReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/campaign-plan': {
      id: '/print/campaign-plan'
      path: '/print/campaign-plan'
      fullPath: '/print/campaign-plan'
      preLoaderRoute: typeof PrintCampaignPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/new': {
      id: '/campaign/new'
      path: '/campaign/new'
      fullPath: '/campaign/new'
      preLoaderRoute: typeof CampaignNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId': {
      id: '/campaign/$campaignId'
      path: '/campaign/$campaignId'
      fullPath: '/campaign/$campaignId'
      preLoaderRoute: typeof CampaignCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId_/run/$testId': {
      id: '/campaign/$campaignId_/run/$testId'
      path: '/campaign/$campaignId/run/$testId'
      fullPath: '/campaign/$campaignId/run/$testId'
      preLoaderRoute: typeof CampaignCampaignIdRunTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$campaignId_/execute/$testId': {
      id: '/campaign/$campaignId_/execute/$testId'
      path: '/campaign/$campaignId/execute/$testId'
      fullPath: '/campaign/$campaignId/execute/$testId'
      preLoaderRoute: typeof CampaignCampaignIdExecuteTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BaselineRoute: BaselineRoute,
  ComplianceRoute: ComplianceRoute,
  ComponentsRoute: ComponentsRoute,
  DashboardRoute: DashboardRoute,
  DiffRoute: DiffRoute,
  GraphRoute: GraphRoute,
  ImpactAnalysisRoute: ImpactAnalysisRoute,
  LoginRoute: LoginRoute,
  PreferencesRoute: PreferencesRoute,
  ProductRoute: ProductRoute,
  QueryRoute: QueryRoute,
  RequirementsRoute: RequirementsRoute,
  SchemaRoute: SchemaRoute,
  SearchRoute: SearchRoute,
  TestsRoute: TestsRoute,
  VersionDiffRoute: VersionDiffRoute,
  VersioningRoute: VersioningRoute,
  WorkspaceRoute: WorkspaceRoute,
  CampaignCampaignIdRoute: CampaignCampaignIdRoute,
  CampaignNewRoute: CampaignNewRoute,
  PrintCampaignPlanRoute: PrintCampaignPlanRoute,
  PrintCampaignReportRoute: PrintCampaignReportRoute,
  PrintDashboardRoute: PrintDashboardRoute,
  PrintImpactAnalysisRoute: PrintImpactAnalysisRoute,
  PrintQueryResultRoute: PrintQueryResultRoute,
  PrintRequirementsRoute: PrintRequirementsRoute,
  PrintTestsRoute: PrintTestsRoute,
  ReqReqIdRoute: ReqReqIdRoute,
  ReqNewRoute: ReqNewRoute,
  TestTestIdRoute: TestTestIdRoute,
  TestNewRoute: TestNewRoute,
  CampaignCampaignIdExecuteTestIdRoute: CampaignCampaignIdExecuteTestIdRoute,
  CampaignCampaignIdRunTestIdRoute: CampaignCampaignIdRunTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
