/** GH27 — root repo of the public "Lave-linge LL800" demo workspace (generated by
 *  scripts/demo-lave-linge/generate.mjs). Its polenta-repo.yaml pulls in the 4 component repos. */
export const DEMO_PROJECT_URL = 'https://github.com/laurentolive/demo-ll800-produit.git'
